#!/usr/bin/env python
import os
import json
import hooks
import sys
import git
root = git.repo_basedir()


with open(os.path.join(root, '.git/hooks/hooks.json'), 'r') as f:
    cfg = json.load(f)

status = {}
for hook in cfg['hooks']:
    status[hook['name']] = getattr(hooks, hook['name'])(**hook.get('options', {}))

if not all(status.values()):
    print('fix error and commit again')
    sys.exit(1)
